apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: psyconnect
  labels:
    app: recommendation-service
spec:
  selector:
    app: recommendation-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
