name: PsyConnect
description: "PsyConnect crossplatform project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
flutter_localizations:
  sdk: flutter
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  flutter_platform_widgets: ^7.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.1.0
  loading_animation_widget: ^1.3.0
  # Toaster
  fluttertoast: ^8.2.10
  # Choose image
  image_picker: ^0.8.7+3
# Provider to save temp data
  provider: ^6.0.5
# Cloudinary
  cloudinary_url_gen: ^1.0.0
  cloudinary_api: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/
    - lang/
    - .env
