name: PsyConnect
description: "PsyConnect crossplatform project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.1.0
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  # Rename
  rename: ^2.1.1
  shared_preferences: ^2.5.3


  get: ^4.7.2
  # Change app icon
  flutter_launcher_icons: ^0.13.1
  flutter_platform_widgets: ^7.0.1
  # Pin code fields
  pin_code_fields: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  # Fonts
  google_fonts: ^6.1.0
  flutter_datetime_picker_plus: ^2.1.0
  # OTP Text Field
  flutter_otp_text_field: ^1.1.0+2
  # Permission Handler
  permission_handler: ^10.2.0
  loading_animation_widget: ^1.3.0
  # Toaster
  fluttertoast: ^8.2.10
  # Choose image
  image_picker: ^0.8.7+3
# Provider to save temp data
  provider: ^6.0.5
# Cloudinary
  cloudinary_url_gen: ^1.0.0
  cloudinary_api: ^1.0.0
  timeago: ^3.7.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  cloud_firestore: ^5.6.6
# Firebase chat
  # firebase_core: ^2.0.0
  # firebase_auth: ^4.0.0
  # cloud_firestore: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gifs/
    - lang/
    - .env
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_psyconnect.png"
