

services:
  apigateway:
    build: ./apigateway
    ports:
      - "8888:8888"
    depends_on:
      - identityservice
      - profileservice
    networks:
      - psyconnect-network
    env_file:
      - .env

  identityservice:
    build: ./identityservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/identityservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD_IDENTITY_SERVICE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SIGNER_KEY: ${JWT_SIGNER_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - db
      - profileservice
      - notificationservice
    networks:
      - psyconnect-network
    env_file:
      - .env

  profileservice:
    build: ./profileservice
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD_PROFILE_SERVICE}
    ports:
      - "8081:8081"
    depends_on:
      - neo4j
    networks:
      - psyconnect-network
    env_file:
      - .env

  notificationservice:
    build: ./notificationservice
#    depends_on:
#      - redis
#    environment:
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
    ports:
      - "8082:8082"
    networks:
      - psyconnect-network
    env_file:
      - .env

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD_IDENTITY_SERVICE}
      MYSQL_DATABASE: identityservice
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    networks:
      - psyconnect-network

  neo4j:
    image: neo4j:5
    restart: always
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD_PROFILE_SERVICE}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    networks:
      - psyconnect-network

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    networks:
      - psyconnect-network

volumes:
  db-data:
  neo4j-data:

networks:
  psyconnect-network:
    driver: bridge
