// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: get_profile.proto

package gprc_grpc_generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_get_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_get_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Profile       *ProfileData           `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_get_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_get_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetProfileResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetProfileResponse) GetProfile() *ProfileData {
	if x != nil {
		return x.Profile
	}
	return nil
}

type ProfileData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	DateOfBirth   string                 `protobuf:"bytes,8,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileData) Reset() {
	*x = ProfileData{}
	mi := &file_get_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileData) ProtoMessage() {}

func (x *ProfileData) ProtoReflect() protoreflect.Message {
	mi := &file_get_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileData.ProtoReflect.Descriptor instead.
func (*ProfileData) Descriptor() ([]byte, []int) {
	return file_get_profile_proto_rawDescGZIP(), []int{2}
}

func (x *ProfileData) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *ProfileData) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ProfileData) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ProfileData) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ProfileData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfileData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ProfileData) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *ProfileData) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

type GetProfileBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileIds    []string               `protobuf:"bytes,1,rep,name=profile_ids,json=profileIds,proto3" json:"profile_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileBatchRequest) Reset() {
	*x = GetProfileBatchRequest{}
	mi := &file_get_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileBatchRequest) ProtoMessage() {}

func (x *GetProfileBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_get_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileBatchRequest.ProtoReflect.Descriptor instead.
func (*GetProfileBatchRequest) Descriptor() ([]byte, []int) {
	return file_get_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfileBatchRequest) GetProfileIds() []string {
	if x != nil {
		return x.ProfileIds
	}
	return nil
}

type GetProfileBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Profiles      []*ProfileData         `protobuf:"bytes,3,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileBatchResponse) Reset() {
	*x = GetProfileBatchResponse{}
	mi := &file_get_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileBatchResponse) ProtoMessage() {}

func (x *GetProfileBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileBatchResponse.ProtoReflect.Descriptor instead.
func (*GetProfileBatchResponse) Descriptor() ([]byte, []int) {
	return file_get_profile_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetProfileBatchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetProfileBatchResponse) GetProfiles() []*ProfileData {
	if x != nil {
		return x.Profiles
	}
	return nil
}

var File_get_profile_proto protoreflect.FileDescriptor

const file_get_profile_proto_rawDesc = "" +
	"\n" +
	"\x11get_profile.proto\x12\aprofile\"2\n" +
	"\x11GetProfileRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\"\x83\x01\n" +
	"\x12GetProfileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12.\n" +
	"\aprofile\x18\x03 \x01(\v2\x14.profile.ProfileDataR\aprofile\"\xe8\x01\n" +
	"\vProfileData\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x12\"\n" +
	"\rdate_of_birth\x18\b \x01(\tR\vdateOfBirth\"9\n" +
	"\x16GetProfileBatchRequest\x12\x1f\n" +
	"\vprofile_ids\x18\x01 \x03(\tR\n" +
	"profileIds\"\x8a\x01\n" +
	"\x17GetProfileBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x120\n" +
	"\bprofiles\x18\x03 \x03(\v2\x14.profile.ProfileDataR\bprofiles2\xad\x01\n" +
	"\x0eProfileService\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.profile.GetProfileRequest\x1a\x1b.profile.GetProfileResponse\x12T\n" +
	"\x0fGetProfileBatch\x12\x1f.profile.GetProfileBatchRequest\x1a .profile.GetProfileBatchResponseBj\n" +
	"\x1bdev.psyconnect.grpc.profileP\x01ZIconsultationservice/internal/grpc/gprc.grpc_generated;gprc_grpc_generatedb\x06proto3"

var (
	file_get_profile_proto_rawDescOnce sync.Once
	file_get_profile_proto_rawDescData []byte
)

func file_get_profile_proto_rawDescGZIP() []byte {
	file_get_profile_proto_rawDescOnce.Do(func() {
		file_get_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_profile_proto_rawDesc), len(file_get_profile_proto_rawDesc)))
	})
	return file_get_profile_proto_rawDescData
}

var file_get_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_get_profile_proto_goTypes = []any{
	(*GetProfileRequest)(nil),       // 0: profile.GetProfileRequest
	(*GetProfileResponse)(nil),      // 1: profile.GetProfileResponse
	(*ProfileData)(nil),             // 2: profile.ProfileData
	(*GetProfileBatchRequest)(nil),  // 3: profile.GetProfileBatchRequest
	(*GetProfileBatchResponse)(nil), // 4: profile.GetProfileBatchResponse
}
var file_get_profile_proto_depIdxs = []int32{
	2, // 0: profile.GetProfileResponse.profile:type_name -> profile.ProfileData
	2, // 1: profile.GetProfileBatchResponse.profiles:type_name -> profile.ProfileData
	0, // 2: profile.ProfileService.GetProfile:input_type -> profile.GetProfileRequest
	3, // 3: profile.ProfileService.GetProfileBatch:input_type -> profile.GetProfileBatchRequest
	1, // 4: profile.ProfileService.GetProfile:output_type -> profile.GetProfileResponse
	4, // 5: profile.ProfileService.GetProfileBatch:output_type -> profile.GetProfileBatchResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_get_profile_proto_init() }
func file_get_profile_proto_init() {
	if File_get_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_profile_proto_rawDesc), len(file_get_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_get_profile_proto_goTypes,
		DependencyIndexes: file_get_profile_proto_depIdxs,
		MessageInfos:      file_get_profile_proto_msgTypes,
	}.Build()
	File_get_profile_proto = out.File
	file_get_profile_proto_goTypes = nil
	file_get_profile_proto_depIdxs = nil
}
