spring.application.name=api_service
server.port=8888
base.url=http://localhost
SIGNER_KEY=5f2a6e8ffb0fd3cbac079162c3168a2c2dfb5b115a7119ef38dd5fb1553295...
BOOTSTRAP_ADDRESS=127.0.0.1:9092
spring.cloud.gateway.routes[0].id=public_routes
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/login,/auth/register
spring.cloud.gateway.routes[0].filters[0]=RemoveRequestHeader=Authorization
spring.cloud.gateway.routes[0].filters[1]=RemoveRequestHeader=Forwarded
spring.cloud.gateway.routes[1].id=identity_service
spring.cloud.gateway.routes[1].uri=http://localhost:8080
spring.cloud.gateway.routes[1].predicates[0]=Path=/identity/**,/auth/**,/oauth2/**,/account/**
spring.cloud.gateway.routes[2].id=profile_service
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/profile/**,/profile/friends/**,/mood/**,/user-setting/**
spring.cloud.gateway.routes[3].id=notification_service
spring.cloud.gateway.routes[3].uri=http://localhost:8082
spring.cloud.gateway.routes[3].predicates[0]=Path=/noti/**
spring.cloud.gateway.routes[4].id=consultation_service
spring.cloud.gateway.routes[4].uri=http://localhost:8084
spring.cloud.gateway.routes[4].predicates[0]=Path=/consultation/**
baseUriNotificationService=localhost
baseUriProfileService=localhost
logging.level.org.springframework.web=INFO
logging.level.org.springframework.cloud.gateway=INFO
spring.cloud.gateway.forwarded.enabled=false
