apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultation-service
  namespace: psyconnect
  labels:
    app: consultation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultation-service
  template:
    metadata:
      labels:
        app: consultation-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: consultation-service
          image: hiamchubbybear/psyconnect-consultation-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: psyconnect-config
            - secretRef:
                name: psyconnect-secrets
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: psyconnect-secrets
                  key: CONSULTATION_MONGO_URI
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m -Djava.net.preferIPv4Stack=true"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 90
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
