# Bitnami Kafka Helm Chart Values
# Repo: https://charts.bitnami.com/bitnami
# Cmd: helm install kafka bitnami/kafka -f k8s/infrastructure/kafka-values.yaml

zookeeper:
  enabled: false # Use Kraft

image:
  tag: latest

controller:
  replicaCount: 1
  resourcesPreset: "micro"

broker:
  replicaCount: 1
  resourcesPreset: "micro"

listeners:
  client:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT

service:
  type: ClusterIP
  ports:
    client: 9092

persistence:
  enabled: true
  size: 2Gi
