# Bitnami Redis Helm Chart Values
# Repo: https://charts.bitnami.com/bitnami
# Cmd: helm install redis bitnami/redis -f k8s/infrastructure/redis-values.yaml

auth:
  enabled: false # Easier for dev, enable password in prod

image:
  tag: latest

architecture: standalone

master:
  persistence:
    enabled: true
    size: 1Gi
  service:
    type: ClusterIP
    port: 6379
  resourcesPreset: "micro"

metrics:
  enabled: false # Save resources
