version: "3.9"

services:
  # API Gateway
  apigateway:
    build:
      context: .
      dockerfile: ./apigateway/Dockerfile
    container_name: apigateway
    ports:
      - "8888:8888"
    depends_on:
      - identityservice
    networks:
      - psyconnect-network
    env_file:
      - .env
    restart: unless-stopped

  # Identity Service
  identityservice:
    build:
      context: ./
      dockerfile: ./identityservice/Dockerfile.debug
    container_name: identityservice
    ports:
      - "8080:8080"

    networks:
      - psyconnect-network
    env_file:
      - .env
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - psyconnect-network
    restart: unless-stopped
volumes:

networks:
  psyconnect-network:
    driver: bridge
