version: '3.9'
services:
#  consultation-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: consultation_service
#    ports:
#      - "${SERVICE_PORT}:${SERVICE_PORT}"
#    environment:
#      SERVICE_ENV: ${SERVICE_ENV}
#      SERVICE_PORT: ${SERVICE_PORT}
#      DB_HOST: ${DB_HOST}
#      DB_PORT: ${DB_PORT}
#      DB_USER: ${DB_USER}
#      DB_PASS: ${DB_PASS}
#      DB_NAME: ${DB_NAME}
#    depends_on:
#      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: