

spring.application.name=profileservice
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}

spring.data.neo4j.database=neo4j
spring.neo4j.uri=${SPRING_NEO4J_URI}
spring.neo4j.authentication.username=${SPRING_NEO4J_AUTHENTICATION_USERNAME}
spring.neo4j.authentication.password=${SPRING_NEO4J_AUTHENTICATION_PASSWORD}
spring.data.redis.database=0
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.timeout=60000
server.port=8081
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
logging.level.org.springframework.web=INFO
logging.level.org.springframework.web.servlet.DispatcherServlet=INFO
logging.level.org.springframework.web.servlet=INFO
logging.level.feign=DEBUG
logging.level.org.apache.kafka.clients.NetworkClient=OFF
grpc.server.port=50051
grpc.server.address=0.0.0.0
BOOTSTRAP_ADDRESS=${KAFKA_BROKERS:localhost:19092}
spring.kafka.bootstrap-servers=${BOOTSTRAP_ADDRESS}

spring.kafka.consumer.group-id=profile-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.retries=0
spring.kafka.producer.properties.request.timeout.ms=3000
spring.kafka.producer.properties.delivery.timeout.ms=3000
spring.kafka.producer.properties.linger.ms=0
spring.kafka.producer.properties.max.in.flight.requests.per.connection=1
spring.kafka.producer.properties.max.block.ms=100
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
