// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: check_existed_profile.proto

package gprc_grpc_generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfileId     string                 `protobuf:"bytes,1,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileRequest) Reset() {
	*x = ProfileRequest{}
	mi := &file_check_existed_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileRequest) ProtoMessage() {}

func (x *ProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_check_existed_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileRequest.ProtoReflect.Descriptor instead.
func (*ProfileRequest) Descriptor() ([]byte, []int) {
	return file_check_existed_profile_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

type ProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResponse) Reset() {
	*x = ProfileResponse{}
	mi := &file_check_existed_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResponse) ProtoMessage() {}

func (x *ProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_check_existed_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResponse.ProtoReflect.Descriptor instead.
func (*ProfileResponse) Descriptor() ([]byte, []int) {
	return file_check_existed_profile_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_check_existed_profile_proto protoreflect.FileDescriptor

const file_check_existed_profile_proto_rawDesc = "" +
	"\n" +
	"\x1bcheck_existed_profile.proto\x12\aprofile\"/\n" +
	"\x0eProfileRequest\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x01 \x01(\tR\tprofileId\")\n" +
	"\x0fProfileResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2^\n" +
	"\x13CheckProfileService\x12G\n" +
	"\x12CheckProfileExists\x12\x17.profile.ProfileRequest\x1a\x18.profile.ProfileResponseB\x15Z\x13gprc.grpc_generatedb\x06proto3"

var (
	file_check_existed_profile_proto_rawDescOnce sync.Once
	file_check_existed_profile_proto_rawDescData []byte
)

func file_check_existed_profile_proto_rawDescGZIP() []byte {
	file_check_existed_profile_proto_rawDescOnce.Do(func() {
		file_check_existed_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_check_existed_profile_proto_rawDesc), len(file_check_existed_profile_proto_rawDesc)))
	})
	return file_check_existed_profile_proto_rawDescData
}

var file_check_existed_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_check_existed_profile_proto_goTypes = []any{
	(*ProfileRequest)(nil),  // 0: profile.ProfileRequest
	(*ProfileResponse)(nil), // 1: profile.ProfileResponse
}
var file_check_existed_profile_proto_depIdxs = []int32{
	0, // 0: profile.CheckProfileService.CheckProfileExists:input_type -> profile.ProfileRequest
	1, // 1: profile.CheckProfileService.CheckProfileExists:output_type -> profile.ProfileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_check_existed_profile_proto_init() }
func file_check_existed_profile_proto_init() {
	if File_check_existed_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_check_existed_profile_proto_rawDesc), len(file_check_existed_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_check_existed_profile_proto_goTypes,
		DependencyIndexes: file_check_existed_profile_proto_depIdxs,
		MessageInfos:      file_check_existed_profile_proto_msgTypes,
	}.Build()
	File_check_existed_profile_proto = out.File
	file_check_existed_profile_proto_goTypes = nil
	file_check_existed_profile_proto_depIdxs = nil
}
