server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-log
    static_configs:
      - targets:
          - localhost
        labels:
          job: app-log
          source: app
          instance: instance-1
          __path__: /var/log/myapp/*.log

    pipeline_stages:
      - json:
          expressions:
            level: level
            service: service
            userId: userId
            action: action
      - labels:
          level:
          service:
          userId:
          action
