name: Consultation Service CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SERVICE_PORT: 8080
  DB_HOST: localhost
  DB_PORT: 27017
  DB_USER: root
  DB_PASS: password
  DB_NAME: consultation

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
        options: >-
          --health-cmd "mongosh --username root --password password --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Build the application
        run: go build -o consultation-service ./cmd

      - name: Run tests
        run: go test ./...

  docker-run:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image locally
        run: docker build -t consultation-service .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 consultation-service
