// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: check_existed_profile.proto

package gprc_grpc_generated

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CheckProfileService_CheckProfileExists_FullMethodName = "/profile.CheckProfileService/CheckProfileExists"
)

// CheckProfileServiceClient is the client API for CheckProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckProfileServiceClient interface {
	CheckProfileExists(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type checkProfileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckProfileServiceClient(cc grpc.ClientConnInterface) CheckProfileServiceClient {
	return &checkProfileServiceClient{cc}
}

func (c *checkProfileServiceClient) CheckProfileExists(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, CheckProfileService_CheckProfileExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckProfileServiceServer is the server API for CheckProfileService service.
// All implementations must embed UnimplementedCheckProfileServiceServer
// for forward compatibility.
type CheckProfileServiceServer interface {
	CheckProfileExists(context.Context, *ProfileRequest) (*ProfileResponse, error)
	mustEmbedUnimplementedCheckProfileServiceServer()
}

// UnimplementedCheckProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckProfileServiceServer struct{}

func (UnimplementedCheckProfileServiceServer) CheckProfileExists(context.Context, *ProfileRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckProfileExists not implemented")
}
func (UnimplementedCheckProfileServiceServer) mustEmbedUnimplementedCheckProfileServiceServer() {}
func (UnimplementedCheckProfileServiceServer) testEmbeddedByValue()                             {}

// UnsafeCheckProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckProfileServiceServer will
// result in compilation errors.
type UnsafeCheckProfileServiceServer interface {
	mustEmbedUnimplementedCheckProfileServiceServer()
}

func RegisterCheckProfileServiceServer(s grpc.ServiceRegistrar, srv CheckProfileServiceServer) {
	// If the following call pancis, it indicates UnimplementedCheckProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckProfileService_ServiceDesc, srv)
}

func _CheckProfileService_CheckProfileExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckProfileServiceServer).CheckProfileExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckProfileService_CheckProfileExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckProfileServiceServer).CheckProfileExists(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckProfileService_ServiceDesc is the grpc.ServiceDesc for CheckProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profile.CheckProfileService",
	HandlerType: (*CheckProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckProfileExists",
			Handler:    _CheckProfileService_CheckProfileExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "check_existed_profile.proto",
}
