// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: matching.proto

package gprc_grpc_generated

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchingRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientProfileId    string                 `protobuf:"bytes,1,opt,name=clientProfileId,proto3" json:"clientProfileId,omitempty"`
	TherapistProfileId string                 `protobuf:"bytes,2,opt,name=therapistProfileId,proto3" json:"therapistProfileId,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MatchingRequest) Reset() {
	*x = MatchingRequest{}
	mi := &file_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingRequest) ProtoMessage() {}

func (x *MatchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingRequest.ProtoReflect.Descriptor instead.
func (*MatchingRequest) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{0}
}

func (x *MatchingRequest) GetClientProfileId() string {
	if x != nil {
		return x.ClientProfileId
	}
	return ""
}

func (x *MatchingRequest) GetTherapistProfileId() string {
	if x != nil {
		return x.TherapistProfileId
	}
	return ""
}

type MatchingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingResponse) Reset() {
	*x = MatchingResponse{}
	mi := &file_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingResponse) ProtoMessage() {}

func (x *MatchingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingResponse.ProtoReflect.Descriptor instead.
func (*MatchingResponse) Descriptor() ([]byte, []int) {
	return file_matching_proto_rawDescGZIP(), []int{1}
}

func (x *MatchingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MatchingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_matching_proto protoreflect.FileDescriptor

const file_matching_proto_rawDesc = "" +
	"\n" +
	"\x0ematching.proto\x12\aprofile\"k\n" +
	"\x0fMatchingRequest\x12(\n" +
	"\x0fclientProfileId\x18\x01 \x01(\tR\x0fclientProfileId\x12.\n" +
	"\x12therapistProfileId\x18\x02 \x01(\tR\x12therapistProfileId\"D\n" +
	"\x10MatchingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2e\n" +
	"\x15CreateMatchingRequest\x12L\n" +
	"\x15CreateMatchingRequest\x12\x18.profile.MatchingRequest\x1a\x19.profile.MatchingResponseB\x15Z\x13gprc.grpc_generatedb\x06proto3"

var (
	file_matching_proto_rawDescOnce sync.Once
	file_matching_proto_rawDescData []byte
)

func file_matching_proto_rawDescGZIP() []byte {
	file_matching_proto_rawDescOnce.Do(func() {
		file_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_matching_proto_rawDesc), len(file_matching_proto_rawDesc)))
	})
	return file_matching_proto_rawDescData
}

var file_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_matching_proto_goTypes = []any{
	(*MatchingRequest)(nil),  // 0: profile.MatchingRequest
	(*MatchingResponse)(nil), // 1: profile.MatchingResponse
}
var file_matching_proto_depIdxs = []int32{
	0, // 0: profile.CreateMatchingRequest.CreateMatchingRequest:input_type -> profile.MatchingRequest
	1, // 1: profile.CreateMatchingRequest.CreateMatchingRequest:output_type -> profile.MatchingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_matching_proto_init() }
func file_matching_proto_init() {
	if File_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_matching_proto_rawDesc), len(file_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matching_proto_goTypes,
		DependencyIndexes: file_matching_proto_depIdxs,
		MessageInfos:      file_matching_proto_msgTypes,
	}.Build()
	File_matching_proto = out.File
	file_matching_proto_goTypes = nil
	file_matching_proto_depIdxs = nil
}
