apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: psyconnect
  labels:
    app: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: identity-service
          image: hiamchubbybear/psyconnect-identity-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: psyconnect-config
            - secretRef:
                name: psyconnect-secrets
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
