version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/12345678
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  redis:
    image: redis:7
    container_name: redis_container
    restart: always
    command: ["redis-server", "--requirepass", "12345678"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  profileservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profile_service
    restart: always
    ports:
      - "8081:8081"
    environment:
      - NEO4J_URI=bolt://neo4j_container:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=12345678
      - REDIS_HOST=redis_container
      - REDIS_PASSWORD=12345678
    depends_on:
      - neo4j
      - redis
    volumes:
      - m2_repo:/root/.m2  # Chia sẻ Maven repository để cache dependencies

volumes:
  neo4j_data:
  neo4j_logs:
  redis_data:
  m2_repo: