apiVersion: v1
kind: ConfigMap
metadata:
  name: psyconnect-config
  namespace: psyconnect
data:
  SPRING_PROFILES_ACTIVE: "k8s"

  KAFKA_BROKERS: "kafka:9092"
  KAFKA_ADDRESS: "kafka:9092"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CONSULTATION_REDIS_ADDRESS: "redis:6379"

  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/psyconnect_dev?sslMode=DISABLED&allowPublicKeyRetrieval=true"

  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "psyconnect_dev"

  SPRING_NEO4J_URI: "neo4j+s://256e7888.databases.neo4j.io"

  IDENTITY_SERVICE_URL: "http://identity-service.psyconnect.svc.cluster.local:8080"
  PROFILE_SERVICE_URL: "http://profile-service.psyconnect.svc.cluster.local:8081"
  NOTIFICATION_SERVICE_URL: "http://notification-service.psyconnect.svc.cluster.local:8082"

  BASE_URI_NOTIFICATION_SERVICE: "http://notification-service.psyconnect.svc.cluster.local:8082"
  BASE_URI_PROFILE_SERVICE: "http://profile-service.psyconnect.svc.cluster.local:8081"

  BASE_URL: "http://identity-service.psyconnect.svc.cluster.local:8080"
