apiVersion: v1
kind: Secret
metadata:
  name: psyconnect-secrets
  namespace: psyconnect
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
  SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"

  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"

  CHAT_MONGO_URI: "${CHAT_MONGO_URI}"

  CONSULTATION_MONGO_URI: "${CONSULTATION_MONGO_URI}"

  SPRING_NEO4J_AUTHENTICATION_USERNAME: "${SPRING_NEO4J_AUTHENTICATION_USERNAME}"
  SPRING_NEO4J_AUTHENTICATION_PASSWORD: "${SPRING_NEO4J_AUTHENTICATION_PASSWORD}"

  CONSULTATION_REDIS_PASSWORD: "${CONSULTATION_REDIS_PASSWORD}"

  SPRING_DATA_REDIS_PASSWORD: "${SPRING_DATA_REDIS_PASSWORD}"

  SIGNER_KEY: "${SIGNER_KEY}"
  JWT_SIGNER_KEY: "${JWT_SIGNER_KEY}"
  JWT_SECRET: "${JWT_SECRET}"
  JWT_EXPIRATION: "${JWT_EXPIRATION}"

  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_ID: "${FACEBOOK_CLIENT_ID}"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_SECRET: "${FACEBOOK_CLIENT_SECRET}"

  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"

  SMPT_HOST: "${SMPT_HOST}"
  SMPT_PORT: "${SMPT_PORT}"
  SMPT_MAIL: "${SMPT_MAIL}"
  SMPT_APP_PASS: "${SMPT_APP_PASS}"
