apiVersion: v1
kind: Secret
metadata:
  name: psyconnect-secrets
  namespace: psyconnect
type: Opaque
stringData:
  # Database Credentials
  DB_USERNAME: "root"
  DB_PASSWORD: "CHANGE_ME_IN_PROD"

  # JWT Configuration
  JWT_SECRET: "CHANGE_ME_TO_A_VERY_LONG_RANDOM_STRING_IN_PROD"
  JWT_EXPIRATION: "86400000"

  # SMTP Configuration (Notification Service)
  SMPT_HOST: "smtp.gmail.com"
  SMPT_PORT: "587"
  SMPT_MAIL: "codemail.noreply@gmail.com"
  SMPT_APP_PASS: "pxvd mmkx gzvu nshn" # Ideally should be changed/rotated
