name: "CD - Deploy to K3s"

on:
  # Chạy thủ công khi muốn deploy lên K3s
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    secrets:
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      CHAT_MONGO_URI: ${{ secrets.CHAT_MONGO_URI }}
      CONSULTATION_MONGO_URI: ${{ secrets.CONSULTATION_MONGO_URI }}
      SPRING_NEO4J_AUTHENTICATION_USERNAME: ${{ secrets.SPRING_NEO4J_AUTHENTICATION_USERNAME }}
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: ${{ secrets.SPRING_NEO4J_AUTHENTICATION_PASSWORD }}
      CONSULTATION_REDIS_PASSWORD: ${{ secrets.CONSULTATION_REDIS_PASSWORD }}
      SPRING_DATA_REDIS_PASSWORD: ${{ secrets.SPRING_DATA_REDIS_PASSWORD }}
      SIGNER_KEY: ${{ secrets.SIGNER_KEY }}
      JWT_SIGNER_KEY: ${{ secrets.JWT_SIGNER_KEY }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
      FACEBOOK_CLIENT_ID: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_ID }}
      FACEBOOK_CLIENT_SECRET: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET }}
      SMPT_HOST: ${{ secrets.SMPT_HOST }}
      SMPT_PORT: ${{ secrets.SMPT_PORT }}
      SMPT_MAIL: ${{ secrets.SMPT_MAIL }}
      SMPT_APP_PASS: ${{ secrets.SMPT_APP_PASS }}
