name: CI - API Gateway

on:
  push:
    branches: ["cicd"]
    paths:
      - 'services/apigateway/**'
      - '.github/workflows/ci-apigateway.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: hiamchubbybear
          password: dckr_pat_LTuO4LaeRlB2Q3JCxLMKRKdG-Rs

      - name: Build & Push API Gateway
        run: |
          echo "Building API Gateway..."
          docker build -f ./services/apigateway/Dockerfile -t hiamchubbybear/apigateway:latest .
          docker push hiamchubbybear/apigateway:latest
          echo "API Gateway build complete"
