name: CI - Chat Service

on:
  push:
    branches: ["cicd"]
    paths:
      - 'services/chatservice/**'
      - '.github/workflows/ci-chatservice.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: hiamchubbybear
          password: dckr_pat_LTuO4LaeRlB2Q3JCxLMKRKdG-Rs

      - name: Build & Push Chat Service
        run: |
          echo "Building Chat Service..."
          docker build -f ./services/chatservice/Dockerfile -t hiamchubbybear/chatservice:latest .
          docker push hiamchubbybear/chatservice:latest
          echo "✅ Chat Service build complete"
