name: "CI - Consultation Service"

on:
  push:
    branches: ["main", "develop"]
    paths:
      - "services/consultationservice/**"
      - ".github/workflows/ci-consultation.yml"
      - ".github/workflows/reusable-build-push.yml"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      service_name: "Consultation Service"
      context_path: "services/consultationservice"
      image_name: "hiamchubbybear/psyconnect-consultation-service"
      registry: "docker.io"
      username: "hiamchubbybear"
    secrets:
      password: ${{ secrets.DOCKERHUB_TOKEN }}
