name: "💬 Chat Service"

on:
  push:
    branches: ["main", "develop"]
    paths:
      - "services/chatservice/**"
      - ".github/workflows/ci-chat.yml"
      - ".github/workflows/reusable-build-push.yml"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      service_name: "Chat Service"
      context_path: "services/chatservice"
      image_name: "hiamchubbybear/psyconnect-chat-service"
      registry: "docker.io"
      username: "hiamchubbybear"
    secrets:
      password: ${{ secrets.DOCKERHUB_TOKEN }}
