name: "👤 Profile Service"

on:
  push:
    branches: ["main", "develop"]
    paths:
      - "services/profileservice/**"
      - ".github/workflows/ci-profile.yml"
      - ".github/workflows/reusable-build-push.yml"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build-push.yml
    with:
      service_name: "Profile Service"
      context_path: "services/profileservice"
      image_name: "hiamchubbybear/psyconnect-profile-service"
      registry: "docker.io"
      username: "hiamchubbybear"
    secrets:
      password: ${{ secrets.DOCKERHUB_TOKEN }}
