name: CI - Build All Services

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: hiamchubbybear
          password: dckr_pat_LTuO4LaeRlB2Q3JCxLMKRKdG-Rs

      - name: Build & Push Services
        run: |
          services=("apigateway" "consultationservice" "identityservice" "notificationservice" "profileservice")

          for service in "${services[@]}"; do
            echo "Building $service"
            # Build from root context with Dockerfile path
            docker build -f ./services/$service/Dockerfile -t hiamchubbybear/$service:latest .
            docker push hiamchubbybear/$service:latest
            echo "Done $service"
          done
