name: Reusable Build and Push

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      context_path:
        required: true
        type: string
      image_name:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: "Dockerfile"
      docker_build_args:
        required: false
        type: string
        default: ""
      registry:
        required: false
        type: string
        default: "ghcr.io"
      username:
        required: true
        type: string
    secrets:
      password:
        required: true

jobs:
  build-push:
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Secret Availability
        run: |
          if [ -z "$DOCKER_PASSWORD" ]; then
            echo "::error::DOCKERHUB_TOKEN is EMPTY! Please check Settings > Secrets > Actions."
            exit 1
          else
            echo "✅ DOCKERHUB_TOKEN is set. Length: ${#DOCKER_PASSWORD}"
          fi
        env:
          DOCKER_PASSWORD: ${{ secrets.password }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.password }}

      - name: Build and Push ${{ inputs.service_name }}
        run: |
          cd ${{ inputs.context_path }}
          if [ -f "mvnw" ]; then
            chmod +x mvnw
            ./mvnw clean package -DskipTests
          fi

          # Build with --no-cache to ensure fresh build
          ARGS=""
          if [ -n "${{ inputs.docker_build_args }}" ]; then
            ARGS="${{ inputs.docker_build_args }}"
          fi
          docker build --no-cache $ARGS -f ${{ inputs.dockerfile }} . --tag ${{ inputs.registry }}/${{ inputs.image_name }}:latest
          docker push ${{ inputs.registry }}/${{ inputs.image_name }}:latest
