services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: "neo4j/12345678"
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
